version: '3'

services:
  web:
    build: .
    image: django_rest_postgres
    ports:
      - "8000:8000"
      - "5022:5022"
    depends_on:
      - "db"
    command: bash -c "../docker_stuff/wait-for-postgres.sh db 5432 django_rest_postgres --
      python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000
      && /usr/sbin/sshd -D"
    volumes:
       - e:/Work/web-frameworks/Python/Django/DjangoRESTPostgres:/usr/src
    environment:
      - PGUSER=docker
      - PGPASSWORD=docker

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=django_rest_postgres
    ports: 
      - "5432:5432"
